### ISSUE TITLE
MapFeatureTiles is missing ? 

### ISSUE THREAD

**Issue by leonard-abusaa** [ngageoint/geopackage-android-map#11]
Hi guys, I was trying the example you put on the home page, and after importing all the packages I have only one class that cannot be resolved: "MapFeatureTiles". I saw that there is a FeatureTiles abstract class and has an implementation in a class called "DefaultFeatureTiles". Is it ok to use that one or I'm missing some packages/dependencies ? 

I'm using this lib version:
implementation "mil.nga.geopackage.map:geopackage-android-map:3.0.2"

Thanks.

**Comment by bosborn** [comment]
You are correct, DefaultFeatureTiles replaced MapFeatureTiles (in geopackage-android 1.3.1) and the geopackage-android-map README example did not get updated.  Fixed now, thanks for finding.
