### ISSUE TITLE
Cannot Get Attribute Table 

### ISSUE THREAD

**Issue by kttary** [ngageoint/geopackage-android-map#15]
Please fill out as much known and relevant information as possible.

#### Version Information:

  * GeoPackage Android Map Version: 3.2
  * GeoPackage Android Map Source: Central Repository
  * Device or Emulator: Emulator
  * Android Studio Version: 3.2.1
  * Google Play services Version: 15.0.1
  * Android SDK Version: 26
  * Platform & OS: Mac OS
  * Other Relevant Libraries: 

#### Expected Results:

  * geoPackage.getAttributesTables(); return list of attribute tables

#### Observed Results:

  * it return zero list

#### Steps to Reproduce:

  1. Create an attribute table from one activity
  2. Fill attribute table with some data
  3. Check if the table and data succesfully created
  3. Open geopackage from another activity
  4. geoPackage.getAttributesTables();  return zero length list

#### Relevant Code:

From main activity i create an attribute table and insert a row succesfully

```java
List<AttributesColumn> columns = new ArrayList<AttributesColumn>();
columns.add(AttributesColumn.createColumn(0, "ITEM", GeoPackageDataType.TEXT, true, ""));
columns.add(AttributesColumn.createColumn(1, "VALUE", GeoPackageDataType.TEXT, true, ""));
AttributesTable table = new AttributesTable("METADATA", columns);
 geoPackage.createAttributesTable(table);

AttributesDao attributesDao = geoPackage.getAttributesDao("METADATA");
AttributesRow newRow = attributesDao.newRow();
newRow.setValue("ITEM", "TEST");
newRow.setValue("VALUE", "A");
long rowId = attributesDao.create(newRow);
```
i check the database from DB Browser for SQLite the attribute and row successfully created. then i close geopackage and open it from another activity

```java
GeoPackage geoPackage = manager.open(dataBase);
List<String> attributeTables = geoPackage.getAttributesTables();
```
unfortunately i get zero length attributes table. Anything wrong from the code? Thank you

**Comment by bosborn** [comment]
Change the attributes table creation code to the following:

```
List<AttributesColumn> columns = new ArrayList<AttributesColumn>();
columns.add(AttributesColumn.createColumn(1, "ITEM", GeoPackageDataType.TEXT, true, ""));
columns.add(AttributesColumn.createColumn(2, "VALUE", GeoPackageDataType.TEXT, true, ""));
geoPackage.createAttributesTableWithId("METADATA", columns);
```

This assumes you want the required id column to be named "id" and at column index 0.  The create attributes table method you were calling only creates the raw attributes table without registering it in the contents table (for those that wish to create their own contents).  It was successfully creating the table (though technically invalid w/o the id column) but not registering it in the GeoPackage contents.  I've [updated the documentation](https://github.com/ngageoint/geopackage-core-java/commit/3cca6e5f9e3d7e55af0e862bfb3342d386287082) to help reflect this.

**Comment by kttary** [comment]
thank you. now it's work
