### ISSUE TITLE
Question: How to insert data as Parcels/Polygons from code?

### ISSUE THREAD

**Issue by AndriusRimk** [ngageoint/geopackage-android-map#16]
**State your question**
How to insert data as Parcels/Polygons from code?

**Additional context**
I want to create a database and add rows of Parcels with points from a different database.
I found that I can create a local database and open it, but not sure how I could easily insert rows of parcels using the interface of this library.

**Comment by bosborn** [comment]
I'm not sure what you are referring to by Parcels (ArcGIS?), but geometries (polygons, geometry collections, linestrings, points, etc) must be saved into GeoPackage Feature Table geometry columns as [Simple Features](https://github.com/ngageoint/simple-features-java) in [Well-Known Bytes](https://github.com/ngageoint/simple-features-wkb-java) (WKB) with a [GeoPackage byte header](https://github.com/ngageoint/geopackage-core-java/blob/d068b4bbedbdc19347d48fcc950c3887999ac0f9/src/main/java/mil/nga/geopackage/geom/GeoPackageGeometryData.java#L25) ([OGC GeoPackage spec](http://www.geopackage.org/spec121/#features)).  Your geometries will need to be in or converted to [WKB](http://portal.opengeospatial.org/files/?artifact_id=25355).

If you have your geometries in WKB, you can [create the GeoPackage geometry data](https://github.com/ngageoint/geopackage-core-java/blob/d068b4bbedbdc19347d48fcc950c3887999ac0f9/src/main/java/mil/nga/geopackage/geom/GeoPackageGeometryData.java#L85) and [set them in the features](https://github.com/ngageoint/geopackage-android/blob/b1b1b3f2af38708a4af6935f026332ec1f4b5eed/geopackage-sdk/src/main/java/mil/nga/geopackage/features/user/FeatureRow.java#L102).  If your data is in another format, you can translate it to a [simple features geometry](https://github.com/ngageoint/simple-features-java/blob/master/src/main/java/mil/nga/sf/Geometry.java) and [set into the feature](https://github.com/ngageoint/geopackage-android/blob/b1b1b3f2af38708a4af6935f026332ec1f4b5eed/geopackage-sdk/src/main/java/mil/nga/geopackage/features/user/FeatureRow.java#L102).  There are currently libraries to help with [GeoJSON](https://github.com/ngageoint/simple-features-geojson-java), [OGC API JSON features](https://github.com/ngageoint/ogc-api-features-json-java), and [projections](https://github.com/ngageoint/simple-features-proj-java).

[Tests for converting simple feature geometries to WKB](https://github.com/ngageoint/simple-features-wkb-java/blob/21db0b06c6228cfed799c1751146a0a4bd5fb550/src/test/java/mil/nga/sf/wkb/test/WKBTestUtils.java#L505).

[Tests for converting GeoPackage geometry bytes with header](https://github.com/ngageoint/geopackage-android/blob/b1b1b3f2af38708a4af6935f026332ec1f4b5eed/geopackage-sdk/src/androidTest/java/mil/nga/geopackage/test/geom/GeoPackageGeometryDataUtils.java#L54)

Some examples that create a feature table and/or insert the geometry rows
* [GeoPackage Example create features](https://github.com/ngageoint/geopackage-android/blob/b1b1b3f2af38708a4af6935f026332ec1f4b5eed/geopackage-sdk/src/androidTest/java/mil/nga/geopackage/test/GeoPackageExample.java#L785)
* [Create features for tests](https://github.com/ngageoint/geopackage-android/blob/0c9bef6719bece74b68188aadc11e67e3cdf2d9e/geopackage-sdk/src/androidTest/java/mil/nga/geopackage/test/TestSetupTeardown.java#L398)
* [Insert features test](https://github.com/ngageoint/geopackage-android/blob/b1b1b3f2af38708a4af6935f026332ec1f4b5eed/geopackage-sdk/src/androidTest/java/mil/nga/geopackage/test/features/user/FeatureUtils.java#L1175)
* [Create feature table and insert features for tests](https://github.com/ngageoint/geopackage-android/blob/a8d621589daa91b404344e61f3089043e570c1c1/geopackage-sdk/src/androidTest/java/mil/nga/geopackage/test/tiles/features/FeatureTileUtils.java#L40)
* OGC API - Features, [converting json to geometries](https://github.com/ngageoint/geopackage-core-java/blob/d068b4bbedbdc19347d48fcc950c3887999ac0f9/src/main/java/mil/nga/geopackage/features/OAPIFeatureCoreGenerator.java#L729),  [building features](https://github.com/ngageoint/geopackage-core-java/blob/d068b4bbedbdc19347d48fcc950c3887999ac0f9/src/main/java/mil/nga/geopackage/features/FeatureCoreGenerator.java#L311),  and [inserting them](https://github.com/ngageoint/geopackage-android/blob/0c9bef6719bece74b68188aadc11e67e3cdf2d9e/geopackage-sdk/src/main/java/mil/nga/geopackage/features/OAPIFeatureGenerator.java#L74)
* [Create features table](https://github.com/ngageoint/geopackage-android-map/blob/f49b2b4bd6bc8db8de5d4fd232b15cafbd19c2e4/geopackage-map/src/androidTest/java/mil/nga/geopackage/map/test/TestUtils.java#L197) and [add feature rows](https://github.com/ngageoint/geopackage-android-map/blob/f49b2b4bd6bc8db8de5d4fd232b15cafbd19c2e4/geopackage-map/src/androidTest/java/mil/nga/geopackage/map/test/TestUtils.java#L292)
* [Insert map edited features](https://github.com/ngageoint/geopackage-mapcache-android/blob/664027a431b193085a50e4a873fff793e56341b9/mapcache/src/main/java/mil/nga/mapcache/GeoPackageMapFragment.java#L3313)
