### ISSUE TITLE
Integration questions

### ISSUE THREAD

**Issue by AndriusRimk** [ngageoint/geopackage-android-map#19]
How can we contact the GeoPackage team for questions related to integration and support?

**Additional context**
As a company, we are interested in integrating the GeoPackage solution to our mobile project for mapping. Still, we would want to start a conversation on possible solutions or feasibility of achieving specific features with GeoPackage or geopackage-android-map SKD's.

Thank you in Advance.

**Comment by bosborn** [comment]
Hi Andrius,
For more than basic GitHub questions, you can email the address at the bottom of [this page](http://ngageoint.github.io/MAGE/) (even though not MAGE related).  Reference the GeoPackage and/or MapCache libraries.
