### ISSUE TITLE
GeoPackageManager - DocumentFile support

### ISSUE THREAD

**Issue by osedok** [ngageoint/geopackage-android-map#20]
@bosborn Hi Brian, I am starting to look at some changes related to the scoped access to storage (https://www.youtube.com/watch?v=UnJ3amzJM94) and was wondering if it would be possible to provide a method allowing import of the geopackage providing DocumentFile instead of File?

I am thinking of method like getDatabaseAtExternalFile(DocumentFile df) ... 

**Additional context**
The scoped storage will be enforced when the app target SDK is 30+

**Comment by bosborn** [comment]
I will look into options for an overloaded method.
